name: CI Phase

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_APP_API_URL: ${{ secrets.NEXT_PUBLIC_APP_API_URL }}
      NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Check Docker version
        run: docker --version

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Pre-build Client
        run: |
          envsubst < .env.example > .env
          cat .env

      - name: Build Client (npm)
        run: npm run build
        continue-on-error: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: danang-culinary-atlas-fe:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/danang-culinary-atlas-fe.tar

      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/danang-culinary-atlas-fe.tar
          retention-days: 7
          compression-level: 6
