name: Main CI/CD Pipeline with Approval

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    uses: givoxxs/Danang-Culinary-Atlas-FE/.github/workflows/test-workflows.yml@ci-cd-flows
    secrets: inherit

  build:
    needs: [test]
    if: github.ref == 'refs/heads/main'
    uses: givoxxs/Danang-Culinary-Atlas-FE/.github/workflows/CI-workflows.yml@ci-cd-flows
    secrets: inherit

  deploy:
    needs: [build,test]
    if: github.ref == 'refs/heads/main'
    uses: givoxxs/Danang-Culinary-Atlas-FE/.github/workflows/CD-workflows.yml@ci-cd-flows
    secrets: inherit